name: open_folder
description: "A Flutter plugin to open folders on Android, iOS, macOS, Windows, and Linux platforms."
version: 0.0.4
homepage: https://github.com/SwanFlutter/open_folder
repository: https://github.com/SwanFlutter/open_folder
issue_tracker: https://github.com/SwanFlutter/open_folder/issues

environment:
  sdk: ^3.12.0
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.example.open_folder
        pluginClass: OpenFolderPlugin
      ios:
        pluginClass: OpenFolderPlugin
      linux:
        pluginClass: OpenFolderPlugin
      macos:
        pluginClass: OpenFolderPlugin
      windows:
        pluginClass: OpenFolderPluginCApi


